#!/bin/bash

# Run tests and get global coverage
coverage=$(go test ./... --cover  | awk '/coverage:/ ' | awk '{if ($1 != "?") print $5; else print "0.0";}' | sed 's/\%//g' | awk '{s+=$1} END {printf "%.2f\n", s/NR}')

# Check if coverage is 100%
if [[ $coverage != "100.00" ]]; then
  echo "Error: global coverage is $coverage%, it should be 100.00%."
  exit 1
fi

packageCommit=$(git rev-parse --short HEAD || echo "")
ref=$(git describe --tags --abbrev=0 "${packageCommit}" 2>/dev/null || git symbolic-ref --short HEAD)
packageVersion=${ref##*/}
package=$(basename "$(pwd)")

cat <<EOF > manifest.go
package $package

var packageName = "$package"
var packageVersion = "$packageVersion"
var packageCommit = "$packageCommit"
var packageDate = "$(date -u +"%Y-%m-%dT%H:%M:%SZ")"
EOF

git add manifest.go
git commit -m "Version $packageVersion: automatic version (commit: $packageCommit)"
git push --no-verify